# Generated by Django 2.2.4 on 2019-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_one', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='location',
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('card', 'card'), ('cash', 'cash'), ('qiwi', 'qiwi')], default='card', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
